### ISSUE TITLE
[ERROR] New tests failed with error code 137

### ISSUE THREAD

**Issue by pandevim** [YouTubeNLP/Backend#26]
#### Description
The new tests from `testing/Testing-scripts` branch #19 failed.

#### To Reproduce
Look at the latest run https://github.com/YouTubeNLP/Backend/runs/959867448

#### Expected behavior
All tests should pass

#### Additional context
This Bug is assigned to @YashSahsani as the suspected error happend in the [test.yml](https://github.com/YouTubeNLP/Backend/blob/master/.github/workflows/test.yml) file where `git blame test.yml` produced YashSahsani as the author.

**Comment by pandevim** [comment]
Github Action workflow for this repository is disable until this issue gets resolved. Feel free to [enable](https://github.com/YouTubeNLP/Backend/settings/actions) it during testing.

**Comment by YashSahsani** [comment]
I don't know why it happened but it is working fine for me you can take a look at it https://github.com/YouTubeNLP/Backend/runs/963011238?check_suite_focus=true
