### ISSUE TITLE
Google/YouTube API quotaExceeded exception.

### ISSUE THREAD

**Issue by pandevim** [YouTubeNLP/Backend#29]
#### Description
If we exceed the request rate limit for youtube data api a [`quotaExceeded`](https://github.com/YouTubeNLP/Backend/runs/963159583?check_suite_focus=true) with error code `403` is generated which needs proper handling. This is happening only for our `tests/` as it creates multiple threads which increase the request to the youtube api linearly. 

#### Possible solutions
1. Change the way we're testing our API, ex. break the load testing and mock testing to separate tests.
2. Initiate the github action event when we make a [pull request](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) to `master` rather than [push](https://github.com/YouTubeNLP/Backend/blob/master/.github/workflows/test.yml#L4).
3. Change quota in the Google API console.

#### Screenshots
![image](https://user-images.githubusercontent.com/31156696/89727072-4003b100-da3f-11ea-899e-2488af5a15c1.png)

#### Helpful resources
Quota usage: https://developers.google.com/youtube/v3/getting-started#quota
Errors: https://developers.google.com/youtube/v3/docs/errors
Quota extension: https://support.google.com/youtube/contact/yt_api_form

**Comment by edward2018211** [comment]
Yep, this is something I am experiencing. Currently it is a blocker for a comments test since when my comments run, I will run into the quotaExceeded error.

**Comment by pandevim** [comment]
Github Action workflow for this repository is disabled until this issue gets resolved. Feel free to [enable](https://github.com/YouTubeNLP/Backend/settings/actions) it during testing.

**Comment by edward2018211** [comment]
I have retested the code and this issue does not reproduce anymore.
<img width="588" alt="Screenshot 2020-09-05 at 11 35 05 AM" src="https://user-images.githubusercontent.com/29204546/92548362-dbe23180-f224-11ea-9039-a6172b0865ee.png">

Still working on getting my pytest to work though.

**Comment by pandevim** [comment]
@edward2018211 
Have you checked he tests with github actions too?
You need to enable them to check it.

**Comment by edward2018211** [comment]
@pandevim I just checked with GitHub Actions and we are getting some errors. I fixed a path error for the Dockerfile.
Currently getting this: 
<img width="491" alt="Screenshot 2020-09-09 at 2 20 06 PM" src="https://user-images.githubusercontent.com/29204546/92638034-acc0d400-f2a7-11ea-9300-f745d8bd52cf.png">

When I fix that error by taking the first 'dot' out, I get another error. Do you know how to solve this?
<img width="496" alt="Screenshot 2020-09-09 at 2 21 35 PM" src="https://user-images.githubusercontent.com/29204546/92638101-c82bdf00-f2a7-11ea-85ff-8b7b0e2b34e5.png">

**Comment by pandevim** [comment]
This seems to be `pytest` is not able to find `settings.py` in the path.  Try to change the import statement to:
```python
import settings
```

**Comment by edward2018211** [comment]
Is ```settings.py``` supposed to be empty? The previous error doesn't reproduce anymore but now I get:
module 'settings.py' has no attribute 'api_key'

**Comment by pandevim** [comment]
That is my mistake, I forgot to delete that file. The correct `settings.py` is present in the root directory: https://github.com/YouTubeNLP/Backend/blob/dev/settings.py

**Comment by edward2018211** [comment]
I have the tests working but I now realize that our tests don't actually make sense. Currently 4 of them fail and I believe that it is because as time goes on, the content we get back from the API will change. For our tests, we have just been copying the response from a certain time point and checking if the current response is the same as the previous response. Maybe we should just check for error code 200 for tests that will change like comments, keywords, etc? We won't change tests like transcript or channel details since those should be the same over time.

**Comment by pandevim** [comment]
You are right, the tests are not made in the best way. The main thing we want want to check is:
1. Schema and data types for particular endpoint
2. Status code
Can you specify which one's are failing?

**Comment by edward2018211** [comment]
Currently these are failing
```
FAILED tests/unit/test_main.py::test_root - AssertionError: assert b'eyJhcGlfc3B...vX2lkfSJ9fX0=' == b'eyJhcGlfc3B...lb19pZH0ifX19'
FAILED tests/unit/test_main.py::test_transcript - AssertionError: assert b'WyJIdWF3ZWk...gW011c2ljXSJd' == b'WyJIdWF3ZWk...NdXNpY10iXQ=='
FAILED tests/unit/test_main.py::test_wordcloud - assert 400 == 200
FAILED tests/unit/test_main.py::test_comment - AttributeError: 'bytes' object has no attribute 'encode'
```
